
RESPONSES = {  'goodbye(.*)' => ['see you later', 'come back later!', 'bye'],
    'bye' => ['see ya!','bbye!','tty later ;)'],
     		  '^hi$|^hello' => ['yes?','hello again','hi back at you'],
              'sayonara' => 'sayonara', 
              'the weather is (.*)' => 'I hate it when it\'s %{c1}', 
              'i like (.*)' => 'I love %{c1} too', 
              # 'i like (.*) test' => 'I love %{c1} test too', 
              'i like (.*)' => 'I dont!', 
              'i groove to (.*) and (.*)' => 'I love %{c1} but I hate %{c2}',
              'how are you?' => 'I\'m feeling good, how are you feeling today?',
              'good ' => 'Great!',
              '(tired|sad|angry|sleepy)' => 'Sorry to hear that you\'re feeling %{c1}',
              '(good|happy|alive)' => 'Oh, that is nice to hear :)',
              'any plans' => 'Just to be awesome!!',
              '(wanna|want to) go.* \bsome[a-z]+?' => ['Depends..what did you have in mind?','Yes','Definitely'],
              '([wanna|want to]) go out?' => 'Maybe.',
              'when' => 'Tomorrow works for me.',
              'when(.*)?' => 'How about next week?',
              'ok' => ['Cool!','That\'s ok'],
              'ok, .*\?' => ['Donno','Maybe'],
              'no' => 'I understand.',
              'yes' => 'ok.',
              'no(.*)do(.*)' => ['Yes I do!','I am pretty sure I do'],
              'how do you like your (.*) ?' => 'I like my %{c1} spicy!!',
              'do you like to (.*), (.*) or (.*)?' => 'You like to %{c1}? Me too! Awesome!'
          }
